src/components/App.vue
src/components/BrigadeDetail.vue
src/components/Leaderboard.vue
src/components/ProjectRow.vue
src/index.html
src/style.scss

Turns links and headers blue and makes "STATUSBOARD" "STATUS BOARD"

Turn links blue

---

.gitignore
README.md
api.js

A couple teeny fixes found while pairing with Ryan to onboard to this project this weekend.

Pair small fixes

---

src/components/App.vue
src/components/BrigadeDetail.vue
src/components/BrigadeMap.vue
src/components/Leaderboard.vue
src/components/Nav.vue
src/components/ProjectDetail.vue
src/components/ProjectRow.vue
src/components/TopicDetail.vue
src/components/Topics.vue
src/style.scss

Created a nav bar, use header levels for content org rather than style, use CfA branding colors.  Sorry for all of the annoying spacing changes that secretly change nothing-- I was using the auto-formatter thing in VS Code.

Header nav

---

README.md

Just downloaded it and got it running. Changes below are based on what I needed to do.
* Remove `dist/data` since that appears to no longer work
* Add instructions for running Memcached via Docker
* Remove CRA boilerplate README

Update README to reflect React dev process

---

package-lock.json
package.json
server.js

This is helpful in developing a new frontend on a different origin.
FYI @mmazanec22 @thadk

Add CORS headers to API

---

statusboard/package.json
statusboard/src/components/ProjectsTable/ProjectsTable.js
statusboard/src/components/ProjectsTable/ProjectsTable.scss
statusboard/src/components/ProjectsTable/TopicsFilter.js
statusboard/src/components/Select/Select.js
statusboard/src/components/commonFormControlStyles.scss
statusboard/src/pages/Brigades/Brigades.js
statusboard/src/pages/Projects.js
statusboard/yarn.lock

This fixes a few small issues with spacing and labels

Fix small style issues

---

statusboard/src/components/ProjectsTable/TopicsFilter.js
statusboard/src/pages/Projects.js

Add a custom filter to make it possible to un-select a topic

Make it possible to not select a topic

---

api/server.js
api/src/api.js
api/src/routes.js

Used async/await where I could instead of nested callbacks and renamed a few variables

Refactor api

---

statusboard/package.json
statusboard/src/components/LoadingIndicator/LoadingIndicator.tsx
statusboard/src/components/MultiSelect/MultiSelect.js
statusboard/src/contexts/BrigadeDataContext.tsx
statusboard/src/pages/Projects/Projects.tsx
statusboard/src/pages/Projects/utils.tsx
statusboard/src/utils/types.ts
statusboard/src/utils/useProjectFilters.ts
statusboard/src/utils/utils.ts
statusboard/tsconfig.json
statusboard/yarn.lock

Closes #67 and abstracts project filtering out of roster

67 limit topics

---

api/src/api.js
api/src/routes.js

This is my first attempt to contribute. Obviously, I didn't do anything new :-)
Main thing, we may object to have this API endpoint within this Github project (I can try to add something similar in the civic-tech-taxonomy).

First version of returning part of the Civic-Tech-Taxonomy.

---

statusboard/public/index.html

@luigi fixed the issue with the preview and icon

fixed the react icon and description in preview

---

statusboard/src/components/PageContents/PageContents.js
statusboard/src/pages/Projects/Projects.tsx

Fixes #41. See [the specs for for (slightly) more information about the option](https://react-table.tanstack.com/docs/api/useFilters#table-options).
Refs. #57.

Fix filter reset on data update

---

statusboard/src/components/Nav/Nav.js

I am looking into #51 a bit. This is not my expertise but I'd argue that closing the hamburger menu after navigation is a better experience.

Fix closing the hamburger menu after navigation

---

statusboard/src/pages/Projects.test.js
statusboard/src/utils/utils.ts

Fixes #90 and a bug while filtering the time range.
The unit test hadn't been updated in a while.

Fixes failing unit test in `Projects.test.js`

---

statusboard/src/pages/Projects.test.js
statusboard/src/pages/Projects/Projects.tsx
statusboard/src/utils/utils.test.js

The bug discovered by @giosce that the link found at https://brigade.codeforamerica.org/priority-action-areas/court-notifications/ showed 0 projects (https://projects.brigade.network/?timeRange=all%20time&topics=courtbot,court-reminder)

Fix incorrect filtering of topics

---

README.md

I just want to highlight a good starting point for anyone wanting to contribute.

Add Shield for "good first issue"

---

api/.eslintrc.json
api/package.json
api/src/api.js

Includes some style related fixes

Change API from airbnb to airbnb-base

---

.github/workflows/run_statusboard_unit_tests.yml

Fixes #92.
Runs the tests on PR and commits.

Add GitHub action for running CRA tests

---

statusboard/src/components/ProjectsTable/ProjectsTable.tsx
statusboard/src/pages/Projects/Projects.tsx

me again :) This should fix issue #102 following @k3KAW8Pnf7mkmdSMPHz27 's very helpful instructions!

fixes issue #102, display correct num of projects

---

api/src/routes.js
statusboard/src/components/Checkbox/Checkbox.js
statusboard/src/pages/Projects/Projects.tsx
statusboard/src/utils/types.ts
statusboard/src/utils/useProjectFilters.ts
statusboard/src/utils/utils.ts

It is still not working, need a little assistance.

Filter by brigade type.

---

statusboard/src/components/Header/Header.js
statusboard/src/components/Header/Header.scss
statusboard/src/components/Header/Header.test.js
statusboard/src/components/Nav/Nav.scss
statusboard/src/pages/Projects/Projects.tsx

Navbar hot-fix

---

statusboard/tsconfig.json

Fix tsconfig.json

---

statusboard/src/components/Map/Map.js
statusboard/src/pages/Brigades/Brigades.js

Not sure there was an open issue about this but we had discussed filtering the projects on the map view by the same time scales as on the projects view. This PR implements that fix.

filter map by time

---

.github/workflows/run-statusboard-lint.yml

Fixes Statusboard unit tests running twice

Fix tests running twice
